import type { AppConfig } from '../../src/config/env';

export const testConfig: AppConfig = {
  NODE_ENV: 'test',
  PORT: 4000,
  HOST: '127.0.0.1',
  APP_BASE_URL: 'http://127.0.0.1:4000',
  LOG_LEVEL: 'silent',
  DATABASE_URL: 'postgresql://user:password@localhost:5432/mono256_my_profile',
  DIRECT_URL: 'postgresql://user:password@localhost:5432/mono256_my_profile',
  CORS_ORIGIN: 'http://localhost:3000',
  JWT_SECRET: 'test_secret_key_which_is_long_enough',
  JWT_EXPIRES_IN: '1d',
  SWAGGER_ENABLED: false,
  RATE_LIMIT_ENABLED: false,
  TRUST_PROXY: false,
  CONTACT_MIN_INTERVAL_SECONDS: 10,
  CONTACT_MAX_BY_IP_PER_HOUR: 30,
  CONTACT_MAX_BY_EMAIL_PER_HOUR: 8,
  CONTACT_DUPLICATE_WINDOW_MINUTES: 60,
  CONTACT_FINGERPRINT_SALT: 'test_contact_fingerprint_salt',
  CONTACT_REQUIRE_TURNSTILE: false,
  TURNSTILE_SECRET_KEY: undefined,
  TURNSTILE_VERIFY_URL: 'https://challenges.cloudflare.com/turnstile/v0/siteverify',
  AUTH_RATE_LIMIT_MAX: 5,
  AUTH_RATE_LIMIT_WINDOW: '1 minute',
  CONTACT_RATE_LIMIT_MAX: 10,
  CONTACT_RATE_LIMIT_WINDOW: '1 minute',
  BOOTSTRAP_ADMIN_ENABLED: false,
  BOOTSTRAP_ADMIN_EMAIL: undefined,
  BOOTSTRAP_ADMIN_NAME: 'Admin User',
  BOOTSTRAP_ADMIN_PASSWORD: undefined,
  BOOTSTRAP_ADMIN_UPDATE_EXISTING: false
};
